function [mus_frame_reg] = register_mus_ref_slice(mus_frame,ref_frame)
%register_mus_ref_slice Register single frames from mus and OCT intensity
%  [mus_frame_reg] = registerImages(mus,ref) Register grayscale images
%  mus and ref using auto-generated code from the Registration
%  Estimator app. The values for all registration parameters were set
%  interactively in the app and result in the registered image stored in
%  the structure array mus_frame_reg.

% Auto-generated by registrationEstimator app on 19-Mar-2024
%-----------------------------------------------------------


% Nonrigid registration
[mus_frame_reg.DisplacementField,mus_frame_reg.RegisteredImage] =...
    imregdemons(mus_frame,ref_frame,100,'AccumulatedFieldSmoothing',...
                1.0,'PyramidLevels',3);

end

